- ros_topic_name: "LHipRoll"
  gz_topic_name: "/model/Nao/joint/LHipRoll/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "LHipYawPitch"
  gz_topic_name: "/model/Nao/joint/LHipYawPitch/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "LHipPitch"
  gz_topic_name: "/model/Nao/joint/LHipPitch/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "LKneePitch"
  gz_topic_name: "/model/Nao/joint/LKneePitch/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "LAnklePitch"
  gz_topic_name: "/model/Nao/joint/LAnklePitch/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "LAnkleRoll"
  gz_topic_name: "/model/Nao/joint/LAnkleRoll/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ